### ISSUE TITLE
Support for Transloco v7

### ISSUE THREAD

**Issue by BThomann** [dscheerens/ngx-transloco-markup#19]
Hello!
Just came across this nice library! Good job here!
Transloco is now published under a new scope `jsverse` https://github.com/jsverse/transloco.
This also resulted into a new version v7 with several breaking changes.
It would be great for this library to also support the new version of transloco, maybe also in the form of a new major version.
Thanks & BR B.

**Comment by dscheerens** [comment]
Ah, thanks for bring that to my attention. I will try to make a new release for that later today

**Comment by dscheerens** [comment]
Just released v6 of this library which supports Transloco v7. Note that it now also requires at least Angular v17 (was 16 previously).

**Comment by BThomann** [comment]
Wow that was quick! Awesome work.
I just noticed that `@ngneat/transloco` is still part of the `peerDependencies`:
https://github.com/dscheerens/ngx-transloco-markup/blob/master/package.json#L36
Shouldn't this also be changed to the new scope & version?

**Comment by BThomann** [comment]
And one suggestion: You could add the different scopes of the package also to the compatibility matrix as an additional information.

**Comment by dscheerens** [comment]
> I just noticed that `@ngneat/transloco` is still part of the `peerDependencies`

Oh, missed that one. Glad you noticed it. Fixed in the 6.0.1 release (just published)

> And one suggestion: You could add the different scopes of the package also to the compatibility matrix as an additional information.

Good suggestion! Added that.

Thanks a lot for your input :+1:

**Comment by BThomann** [comment]
I have to thank you for your work you put into that project! 🚀

**Comment by Morente5** [comment]
Just upgraded from Angular 13 and found @jsverse/transloco@7 is compatible with @angular/core@>=16.0.0 so there is an incompatible combination using this
- @angular/core@16
- @jsverse/transloco@7
- ngx-transloco-markup@6
I think versions of this library should cover the same compatibility options that transloco provides.

Thanks for your awesome libraries!
